export interface Sol {
    sn?: number,
    solCode?: string,
    solDescription?: string,
    postedFlag?: string,
    postedTime?: Date,
    verifiedFlag?: string,
    verifiedTime?: Date,
    deleteFlag?: string,
    phoneNumber?: number,
    emailAddress?: string,
    location?: string,
    postedBy?: string,
    verifiedBy?: string,    
}
