export interface corporateKyc{
    contactPersonName?: string,
    corporateSegment?: string,
    custCode?: string,
    deletedBy?: string,
    deletedFlag?: string,
    deletedTime?: Date,
    headOffice?: string,
    inCorporationDate?: Date,
    joiningDate?: Date,
    kraPin?: string,
    legalEntityType?: string,
    modifiedBy?: string,
    modifiedOn?: Date,
    organisationName?: string,
    postedBy?: string,
    postedFlag?: string,
    postedTime?: Date,
    region?: string,
    registrationPin?: string,
    shortName?: string,
    subSegment?: string,
    verifiedFlag?: string,
    verifiedTime?: Date
  }